#!/bin/sh

if [ -f /Library/LaunchDaemons/com.82flex.trollinstalld.plist ]; then
    launchctl load -w /Library/LaunchDaemons/com.82flex.trollinstalld.plist || true
elif [ -f /var/jb/Library/LaunchDaemons/com.82flex.trollinstalld.plist ]; then
    launchctl load -w /var/jb/Library/LaunchDaemons/com.82flex.trollinstalld.plist || true
else
    ROOTHIDE_PATH=$(ls -d /var/containers/Bundle/Application/.jbroot-*/Library/LaunchDaemons/com.82flex.trollinstalld.plist)
    if [ -f "$ROOTHIDE_PATH" ]; then
        launchctl load -w "$ROOTHIDE_PATH" || true
    fi
fi

killall -9 installd || true

exit 0
